# Reinforcement Learning with TensorFlow

The library `gym` is referneced in some courses. For modernizarion, to use libraries used currently, we import gymnasium

In [2]:
import numpy as np
import gymnasium

In [5]:
env = gymnasium.make("FrozenLake-v1", is_slippery="False")
state_size = env.observation_space.n
action_size = env.action_space.n
 

In [6]:
Q_table = np.zeros((state_size, action_size))
print(Q_table)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
