# Reinforcement Learning with PyTorch

In [5]:
import numpy as np
import gymnasium

In [3]:
env = gymnasium.make("FrozenLake-v1", is_slippery="False")
state_size = env.observation_shape[0]
action_size = env.action_space.n
 

In [6]:
Q_table = np.zeros((state_size, action_size))
print(Q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


alpha : learning rate; gamma : discount factor; epsilon : exploration rate; episodes: number of games

In [11]:
alpha = 0.1
gamma = 0.99
epsilon = 1.0
espsilon_decay = 0.995
epsilon_min = 0.01
episodes = 2000

In [12]:
import torch
import torch.nn as nn
import torch.optim as optim
import random
from collections import deque

In [18]:
class DQN(nn.Module):
    def __init__(self, state_size, action_size):
        super().__init__()
        self.fc1 = nn.Linear(state_size, 24)
        self.fc2 = nn.Linear(24, 24)
        self.fc3 = nn.Linear(24, action_size)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)


In [19]:
DQN = DQN(state_size, action_size)